"""
PerfMind — Document Exporter
Exports generated NFR content to professional .docx format.
Output directory is configured via OUTPUT_DIR in .env file.
"""

import os
import re
from datetime import datetime

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor
from dotenv import load_dotenv

load_dotenv()


class NFRDocumentExporter:
    """
    Exports PerfMind NFR content to a professional Word (.docx) document.
    Output folder is read from OUTPUT_DIR in the .env file.
    """

    def __init__(self):
        self.doc = Document()
        self._output_dir = self._resolve_output_dir()
        self._setup_styles()

    def _resolve_output_dir(self) -> str:
        """
        Read output directory from environment.
        Falls back to ~/PerfMind_Outputs if OUTPUT_DIR is not set.
        """
        output_dir = os.getenv("OUTPUT_DIR", "").strip()

        if not output_dir:
            fallback = os.path.join(os.path.expanduser("~"), "PerfMind_Outputs")
            print(
                f"⚠️  OUTPUT_DIR not set in .env — using default: {fallback}"
            )
            return fallback

        return output_dir

    def _setup_styles(self):
        """Set document default font."""
        style = self.doc.styles["Normal"]
        style.font.name = "Calibri"
        style.font.size = Pt(11)

    def _add_header(self, app_description: str):
        """Add title, subtitle and metadata table at the top of the document."""
        title = self.doc.add_heading("NFR Requirements Document", 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        subtitle = self.doc.add_paragraph()
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = subtitle.add_run("Generated by PerfMind 🧠")
        run.font.size = Pt(12)
        run.font.color.rgb = RGBColor(0x42, 0x42, 0x42)

        table = self.doc.add_table(rows=3, cols=2)
        table.style = "Light Grid Accent 1"
        metadata = [
            ("Generated On", datetime.now().strftime("%B %d, %Y at %H:%M")),
            ("Application", app_description[:120]),
            ("Document Version", "1.0 — Draft"),
        ]
        for i, (label, value) in enumerate(metadata):
            table.rows[i].cells[0].text = label
            table.rows[i].cells[1].text = value

        self.doc.add_paragraph()

    def _parse_and_add_content(self, content: str):
        """
        Parse the generated markdown-style content and add it
        to the Word document with appropriate formatting.
        """
        lines = content.split("\n")

        for line in lines:
            line = line.strip()
            if not line:
                continue

            if line.startswith("## "):
                self.doc.add_heading(line[3:], level=1)

            elif line.startswith("### "):
                self.doc.add_heading(line[4:], level=2)

            elif line.startswith("#### "):
                self.doc.add_heading(line[5:], level=3)

            elif line.startswith("|") and line.endswith("|"):
                self._add_table_row(line)

            elif line.startswith("- ") or line.startswith("* "):
                self.doc.add_paragraph(line[2:], style="List Bullet")

            elif line.startswith(">"):
                p = self.doc.add_paragraph()
                p.style = "Quote"
                p.add_run(line[1:].strip())

            elif line.startswith("→"):
                self.doc.add_paragraph(line, style="List Bullet")

            elif not line.startswith("---"):
                self.doc.add_paragraph(line)

    def _add_table_row(self, line: str):
        """Add a table row from a pipe-delimited markdown line."""
        # Skip separator rows e.g. |---|---|
        if re.match(r"^\|[\s\-\|]+\|$", line):
            return
        cells = [c.strip() for c in line.split("|") if c.strip()]
        if cells:
            table = self.doc.add_table(rows=1, cols=len(cells))
            table.style = "Light Grid Accent 1"
            for i, text in enumerate(cells):
                table.rows[0].cells[i].text = text

    def _add_footer(self):
        """Add a footer crediting PerfMind."""
        self.doc.add_paragraph()
        footer = self.doc.add_paragraph()
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = footer.add_run(
            "Generated by PerfMind — AI-powered Requirements Generator\n"
            "github.com/shivamsinghal1123/perfmind"
        )
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    def export(self, content: str, app_description: str) -> str:
        """
        Export NFR content to a timestamped .docx file.

        Args:
            content:         Generated NFR text from Claude API
            app_description: Original application description

        Returns:
            Full path to the saved .docx file
        """
        os.makedirs(self._output_dir, exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = os.path.join(
            self._output_dir,
            f"NFR_Requirements_{timestamp}.docx"
        )

        self._add_header(app_description)
        self._parse_and_add_content(content)
        self._add_footer()

        self.doc.save(filename)
        return filename
