"""
PerfMind — Document Exporter
Converts generated NFR content to professional .docx format
"""

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from datetime import datetime
import os
import re


class NFRDocumentExporter:
    """
    Exports PerfMind NFR content to professional Word documents
    """

    def __init__(self):
        self.doc = Document()
        self._setup_styles()

    def _setup_styles(self):
        """Set up document styles and fonts"""
        # Set default font
        style = self.doc.styles['Normal']
        style.font.name = 'Calibri'
        style.font.size = Pt(11)

    def _add_header(self, app_description: str):
        """Add professional document header"""
        # Title
        title = self.doc.add_heading('NFR Requirements Document', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Subtitle
        subtitle = self.doc.add_paragraph()
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = subtitle.add_run('Generated by PerfMind 🧠')
        run.font.size = Pt(12)
        run.font.color.rgb = RGBColor(0x42, 0x42, 0x42)

        # Metadata table
        table = self.doc.add_table(rows=3, cols=2)
        table.style = 'Light Grid Accent 1'
        cells = [
            ('Generated On', datetime.now().strftime("%B %d, %Y at %H:%M")),
            ('Application', app_description[:100]),
            ('Document Version', '1.0 — Draft'),
        ]
        for i, (label, value) in enumerate(cells):
            table.rows[i].cells[0].text = label
            table.rows[i].cells[1].text = value

        self.doc.add_paragraph()

    def _parse_and_add_content(self, content: str):
        """Parse markdown-like content and add to document"""
        lines = content.split('\n')

        for line in lines:
            line = line.strip()
            if not line:
                continue

            # Headers
            if line.startswith('## '):
                self.doc.add_heading(line[3:], level=1)
            elif line.startswith('### '):
                self.doc.add_heading(line[4:], level=2)
            elif line.startswith('#### '):
                self.doc.add_heading(line[5:], level=3)

            # Tables — detect pipe-separated rows
            elif line.startswith('|') and line.endswith('|'):
                self._handle_table_line(line)

            # Bullet points
            elif line.startswith('- ') or line.startswith('* '):
                self.doc.add_paragraph(
                    line[2:],
                    style='List Bullet'
                )

            # Blockquotes / notices
            elif line.startswith('>'):
                p = self.doc.add_paragraph()
                p.style = 'Quote'
                p.add_run(line[1:].strip())

            # Arrow points
            elif line.startswith('→'):
                p = self.doc.add_paragraph()
                p.add_run(line).bold = False
                p.style = 'List Bullet'

            # Regular paragraph
            elif not line.startswith('---'):
                self.doc.add_paragraph(line)

    def _handle_table_line(self, line: str):
        """Basic table row handler"""
        # Skip separator rows like |---|---|
        if re.match(r'^\|[\s\-\|]+\|$', line):
            return
        cells = [c.strip() for c in line.split('|') if c.strip()]
        if cells:
            table = self.doc.add_table(rows=1, cols=len(cells))
            table.style = 'Light Grid Accent 1'
            for i, cell_text in enumerate(cells):
                table.rows[0].cells[i].text = cell_text

    def _add_footer(self):
        """Add professional footer"""
        self.doc.add_paragraph()
        footer_p = self.doc.add_paragraph()
        footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = footer_p.add_run(
            'Generated by PerfMind — AI-powered Requirements Generator\n'
            'github.com/shivamsinghal1123/perfmind'
        )
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    def export(
        self,
        content: str,
        app_description: str
    ) -> str:
        """
        Export NFR content to .docx file

        Args:
            content: Generated NFR content from Claude
            app_description: Original application description
            output_dir: Directory to save file

        Returns:
            Path to saved .docx file
        """
        
        # Create outputs directory if it doesn't exist
        os.makedirs("outputs", exist_ok=True)

        # Generate filename with timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"outputs/NFR_Requirements_{timestamp}.md"

        self._add_header(app_description)
        self._parse_and_add_content(content)
        self._add_footer()

        self.doc.save(filename)
        return filename