"""
PerfMind — Utility Functions
"""

import os
from datetime import datetime


def print_banner():
    """Print the PerfMind ASCII banner."""
    banner = """
██████╗ ███████╗██████╗ ███████╗███╗   ███╗██╗███╗   ██╗██████╗ 
██╔══██╗██╔════╝██╔══██╗██╔════╝████╗ ████║██║████╗  ██║██╔══██╗
██████╔╝█████╗  ██████╔╝█████╗  ██╔████╔██║██║██╔██╗ ██║██║  ██║
██╔═══╝ ██╔══╝  ██╔══██╗██╔══╝  ██║╚██╔╝██║██║██║╚██╗██║██║  ██║
██║     ███████╗██║  ██║██║     ██║ ╚═╝ ██║██║██║ ╚████║██████╔╝
╚═╝     ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚═════╝ 

        🧠 AI-powered NFR Requirements Generator
        Built by a Performance Engineer, for Performance Engineers
    """
    print(banner)


def save_output(content: str, app_description: str) -> str:
    """
    Save generated NFR requirements to a markdown file.

    Args:
        content: Generated NFR document content
        app_description: Original application description (used for filename)

    Returns:
        Path to saved file
    """
    # Create outputs directory if it doesn't exist
    os.makedirs("outputs", exist_ok=True)

    # Generate filename with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"outputs/NFR_Requirements_{timestamp}.md"

    # Build full document
    full_content = f"""# NFR Requirements Document
Generated by PerfMind 🧠
Date: {datetime.now().strftime("%B %d, %Y at %H:%M")}

## Application Description
{app_description}

---

{content}

---
*Generated by PerfMind — AI-powered Requirements Generator for Performance Engineers*
*GitHub: https://github.com/shivamsinghal1123/perfmind*
"""

    with open(filename, "w", encoding="utf-8") as f:
        f.write(full_content)

    return filename


def format_section(title: str, content: str) -> str:
    """Format a section with consistent styling."""
    return f"\n{'='*60}\n{title}\n{'='*60}\n{content}\n"
